name: Daily Weather Notification

on:
  schedule:
    - cron: "0 6 * * *"  # 6:00 UTC = 7:00 AM UK time

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run notification script
        run: python daily_run.py
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          PUSHOVER_APP_TOKEN: ${{ secrets.PUSHOVER_APP_TOKEN }}
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
          LAT: "51.5074"
          LON: "-0.1278"

